In [1]:
import numpy as np

##NUMPY INDEXING AND SELECTION

In [2]:
test_array = np.arange(0,10)

In [3]:
test_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
test_array[3]

3

In [5]:
test_array[7]

7

In [6]:
test_array[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
test_array[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
test_array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
test_array[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
test_array[3:]

array([3, 4, 5, 6, 7, 8, 9])

NUMPY ARRAYS HAVE BROADCASTING CAPABILITY.PARTS OF ARRAY CAN BE ASSIGNED TO ANOTHER VARIABLE, WHICH IS NOT POSSIBLE IN PYTHON LISTS

In [11]:
test_array[0:5] = 100

In [12]:
test_array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [13]:
test_array = np.arange(0,10)

In [14]:
slice_of_array = test_array[0:5]

In [15]:
test_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
slice_of_array

array([0, 1, 2, 3, 4])

numpy arrays can be sliced and can be assigned to another variable


In [17]:
slice_of_array[:] = 90

In [18]:
test_array

array([90, 90, 90, 90, 90,  5,  6,  7,  8,  9])

here slice of array is a part of test array and when slice of array is changed that change is reflected in test array


In [19]:
test_array_copy = test_array.copy()

In [20]:
test_array_copy[:] = 88

In [21]:
test_array_copy

array([88, 88, 88, 88, 88, 88, 88, 88, 88, 88])

In [22]:
test_array

array([90, 90, 90, 90, 90,  5,  6,  7,  8,  9])

note that making a copy of an array and changing its items will not change original array

In [23]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array_2d[1]

array([4, 5, 6])

In [26]:
array_2d[2]

array([7, 8, 9])

In [27]:
array_2d[1][2]

6

In [28]:
array_2d[2,2]

9

In [29]:
array_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
array_2d[:2,1:]

array([[2, 3],
       [5, 6]])

accessed rows from 0 upto but not including 2 in first step and then that is modified to access everything from first column upto the last column. this type of notation is not common but just in case, get familiar with it

In [31]:
my_array = np.arange(1,11)

In [32]:
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
my_array>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [34]:
bool_arr = my_array>5

In [35]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [36]:
my_array[bool_arr]

array([ 6,  7,  8,  9, 10])

In [37]:
my_array[my_array>8]

array([ 9, 10])

NUMPY OPERATIONS:


In [38]:
np.random.randn(2,3,4)

array([[[-5.60429958e-01, -1.15753843e+00, -7.76859052e-01,
          6.76718795e-01],
        [ 1.57190167e+00, -1.36632528e+00,  5.77928011e-01,
          1.82959474e-01],
        [-5.95764785e-01,  4.44858008e-01,  1.29425915e+00,
          5.29286588e-01]],

       [[ 4.17692118e-01, -5.82510268e-01,  1.09637390e+00,
          1.05214326e+00],
        [ 7.74280842e-01,  1.84780833e-01, -4.30546256e-01,
          5.76444192e-04],
        [ 3.47493189e-01,  3.65743469e-01,  2.40443430e-01,
         -6.97845424e-01]]])

In [39]:
arr_1053 = np.arange(10)

In [40]:
arr_1053

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr_1053 + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
arr_1053 *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
arr_1053 / arr_1053

C:\Users\NithinNazar\AppData\Local\Temp\ipykernel_10660\352255956.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr_1053 / arr_1053


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [44]:
1/0

ZeroDivisionError: division by zero

In [ ]:
2/arr_1053

BASIC ARITHMATIC OPERATIONS IS DONE ON ELEMENT WISE IN AN ARRAY.
DIVIDING AN ELEMENT IN AN ARRAY BY ZERO OR ZERO DIVIDED BY ZERO GIVES WARNING NOT ACTUAL ERRORS. THIS CAN BE DANGEROUS. LOOK OUT FOR IT

In [ ]:
np.sqrt(arr_1053)

In [ ]:
np.sin(arr_1053)

In [ ]:
np.cos(arr_1053)

In [ ]:
np.log(arr_1053)

In [ ]:
arr_1053.sum()

In [ ]:
arr_1053.mean()

In [ ]:
arr_1053.var()

In [ ]:
arr_1053.std()

In [ ]:
arr2d = np.arange(0,25).reshape(5,5)

In [ ]:
arr2d

In [ ]:
arr2d.sum()

In [ ]:
arr2d.shape

In [ ]:
arr2d.sum(axis=0)

In [ ]:
arr2d.sum(axis=1)

AXIS IS THE INDEX OF SHAPE OF THR 2D ARRAY. AXIS = 0 IS THE INDEX OF ROWS AND OPERATION IS DONE ACROSS THE ROW.
AXIS =1 IS THE INDEX OF COLUMN AND OPERATION IS DONE ACROSS THE COLUMN

In [ ]:
np.random.rand(5)

In [ ]:
np.random.seed(101)

In [ ]:
np.random.rand(5)

In [ ]:
np.random.rand(5)

In [ ]:
np.random.seed(101)
np.random.rand(5)

In [ ]:
np.random.seed(101)
np.random.rand(5)

In [45]:
nd_arr = np.arange(0,50)

In [46]:
nd_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [54]:
ndr =  np.random.randint(0,100,(2,3,4))

In [55]:
ndr

array([[[31, 25, 55, 29],
        [ 3, 97,  8, 97],
        [ 2, 34, 15, 18]],

       [[19, 88, 97,  7],
        [86, 47, 94, 64],
        [52, 27, 39, 25]]])

In [56]:
ndr.sum()

1059

In [62]:
ndr.sum(axis=0)

array([[ 50, 113, 152,  36],
       [ 89, 144, 102, 161],
       [ 54,  61,  54,  43]])