In [1]:
import numpy as np



creating np array from standard list

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [4]:
my_arr = np.array(my_list)

In [5]:
my_arr = np.array(my_list)

In [6]:
type(my_arr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

numpy identifies the 2x2 array and displays the list as a matrix

In [9]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

arange function is similar to python range function has a start stop and optional step. (0,10) means from zero upto but not
including 10.

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

shape is defined as (rows, columns)


In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
dist = np.linspace(0,20,11)

linspace function returns evenly spaced numbers over a specifed interval.
has a stat and stoping point and how many evenly spaced numbers we need.it includes stoping point

# NOT TO BE CONFUSED WITH PYTHON ARRANGE FUNCTION


In [23]:
len(dist)

11

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

identity matrix

In [28]:
np.random.rand(1)

array([0.53923019])

generates a random number between 0 and 1. including 0 excluding 1

shapes can also be distributed in random like:

In [29]:
np.random.rand(4,3)

array([[0.16535352, 0.81705488, 0.76030893],
       [0.46569473, 0.03049769, 0.33738777],
       [0.12611455, 0.51345261, 0.71323359],
       [0.7742936 , 0.23738907, 0.63772821]])

instead of a tuple rowsxcolumn is given and we get an arrray with all elements falling between 0 and 1

In [30]:
np.random.randn(5)

array([ 0.59645653,  0.52259736, -0.26117235, -1.16763558, -1.05661703])

In [32]:
np.random.randn(3,3)

array([[-0.32617377,  1.65285688, -1.37024524],
       [ 0.80894855,  1.69707822, -0.80663531],
       [ 0.05921889, -2.23609058,  1.33592787]])

returning samples from a standard normal distribution. it can also be arranged in a shape. numbers closer to zero are more likely to appear than number farther to zero. can include negative numbers also